#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagmentExample
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HotelManagmentExample")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCustomerDetail(CustomerDetail instance);
    partial void UpdateCustomerDetail(CustomerDetail instance);
    partial void DeleteCustomerDetail(CustomerDetail instance);
    partial void InsertBillHotel(BillHotel instance);
    partial void UpdateBillHotel(BillHotel instance);
    partial void DeleteBillHotel(BillHotel instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::HotelManagmentExample.Properties.Settings.Default.HotelManagmentExampleConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CustomerDetail> CustomerDetails
		{
			get
			{
				return this.GetTable<CustomerDetail>();
			}
		}
		
		public System.Data.Linq.Table<BillHotel> BillHotels
		{
			get
			{
				return this.GetTable<BillHotel>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CustomerDetails")]
	public partial class CustomerDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Cus_id;
		
		private string _Cus_Name;
		
		private string _Cus_Address;
		
		private string _Cus_Phone;
		
		private string _Cus_dateofbirth;
		
		private string _Cus_Email;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCus_idChanging(string value);
    partial void OnCus_idChanged();
    partial void OnCus_NameChanging(string value);
    partial void OnCus_NameChanged();
    partial void OnCus_AddressChanging(string value);
    partial void OnCus_AddressChanged();
    partial void OnCus_PhoneChanging(string value);
    partial void OnCus_PhoneChanged();
    partial void OnCus_dateofbirthChanging(string value);
    partial void OnCus_dateofbirthChanged();
    partial void OnCus_EmailChanging(string value);
    partial void OnCus_EmailChanged();
    #endregion
		
		public CustomerDetail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cus_id", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Cus_id
		{
			get
			{
				return this._Cus_id;
			}
			set
			{
				if ((this._Cus_id != value))
				{
					this.OnCus_idChanging(value);
					this.SendPropertyChanging();
					this._Cus_id = value;
					this.SendPropertyChanged("Cus_id");
					this.OnCus_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cus_Name", DbType="VarChar(50)")]
		public string Cus_Name
		{
			get
			{
				return this._Cus_Name;
			}
			set
			{
				if ((this._Cus_Name != value))
				{
					this.OnCus_NameChanging(value);
					this.SendPropertyChanging();
					this._Cus_Name = value;
					this.SendPropertyChanged("Cus_Name");
					this.OnCus_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cus_Address", DbType="VarChar(50)")]
		public string Cus_Address
		{
			get
			{
				return this._Cus_Address;
			}
			set
			{
				if ((this._Cus_Address != value))
				{
					this.OnCus_AddressChanging(value);
					this.SendPropertyChanging();
					this._Cus_Address = value;
					this.SendPropertyChanged("Cus_Address");
					this.OnCus_AddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cus_Phone", DbType="VarChar(50)")]
		public string Cus_Phone
		{
			get
			{
				return this._Cus_Phone;
			}
			set
			{
				if ((this._Cus_Phone != value))
				{
					this.OnCus_PhoneChanging(value);
					this.SendPropertyChanging();
					this._Cus_Phone = value;
					this.SendPropertyChanged("Cus_Phone");
					this.OnCus_PhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cus_dateofbirth", DbType="VarChar(50)")]
		public string Cus_dateofbirth
		{
			get
			{
				return this._Cus_dateofbirth;
			}
			set
			{
				if ((this._Cus_dateofbirth != value))
				{
					this.OnCus_dateofbirthChanging(value);
					this.SendPropertyChanging();
					this._Cus_dateofbirth = value;
					this.SendPropertyChanged("Cus_dateofbirth");
					this.OnCus_dateofbirthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cus_Email", DbType="VarChar(50)")]
		public string Cus_Email
		{
			get
			{
				return this._Cus_Email;
			}
			set
			{
				if ((this._Cus_Email != value))
				{
					this.OnCus_EmailChanging(value);
					this.SendPropertyChanging();
					this._Cus_Email = value;
					this.SendPropertyChanged("Cus_Email");
					this.OnCus_EmailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BillHotel")]
	public partial class BillHotel : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Guest_Id;
		
		private string _Guest_Name;
		
		private string _Cuntery;
		
		private string _Phone;
		
		private string _Address;
		
		private string _Gender;
		
		private string _Room_Type;
		
		private string _Room_No;
		
		private string _No_Of_Person;
		
		private string _Children;
		
		private string _Staying_Days;
		
		private string _Total;
		
		private string _Other_Charges;
		
		private string _Sub_Total;
		
		private string _Date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGuest_IdChanging(string value);
    partial void OnGuest_IdChanged();
    partial void OnGuest_NameChanging(string value);
    partial void OnGuest_NameChanged();
    partial void OnCunteryChanging(string value);
    partial void OnCunteryChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnGenderChanging(string value);
    partial void OnGenderChanged();
    partial void OnRoom_TypeChanging(string value);
    partial void OnRoom_TypeChanged();
    partial void OnRoom_NoChanging(string value);
    partial void OnRoom_NoChanged();
    partial void OnNo_Of_PersonChanging(string value);
    partial void OnNo_Of_PersonChanged();
    partial void OnChildrenChanging(string value);
    partial void OnChildrenChanged();
    partial void OnStaying_DaysChanging(string value);
    partial void OnStaying_DaysChanged();
    partial void OnTotalChanging(string value);
    partial void OnTotalChanged();
    partial void OnOther_ChargesChanging(string value);
    partial void OnOther_ChargesChanged();
    partial void OnSub_TotalChanging(string value);
    partial void OnSub_TotalChanged();
    partial void OnDateChanging(string value);
    partial void OnDateChanged();
    #endregion
		
		public BillHotel()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Guest_Id", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Guest_Id
		{
			get
			{
				return this._Guest_Id;
			}
			set
			{
				if ((this._Guest_Id != value))
				{
					this.OnGuest_IdChanging(value);
					this.SendPropertyChanging();
					this._Guest_Id = value;
					this.SendPropertyChanged("Guest_Id");
					this.OnGuest_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Guest_Name", DbType="VarChar(50)")]
		public string Guest_Name
		{
			get
			{
				return this._Guest_Name;
			}
			set
			{
				if ((this._Guest_Name != value))
				{
					this.OnGuest_NameChanging(value);
					this.SendPropertyChanging();
					this._Guest_Name = value;
					this.SendPropertyChanged("Guest_Name");
					this.OnGuest_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cuntery", DbType="VarChar(50)")]
		public string Cuntery
		{
			get
			{
				return this._Cuntery;
			}
			set
			{
				if ((this._Cuntery != value))
				{
					this.OnCunteryChanging(value);
					this.SendPropertyChanging();
					this._Cuntery = value;
					this.SendPropertyChanged("Cuntery");
					this.OnCunteryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(50)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(50)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(50)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this.OnGenderChanging(value);
					this.SendPropertyChanging();
					this._Gender = value;
					this.SendPropertyChanged("Gender");
					this.OnGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Room_Type", DbType="VarChar(50)")]
		public string Room_Type
		{
			get
			{
				return this._Room_Type;
			}
			set
			{
				if ((this._Room_Type != value))
				{
					this.OnRoom_TypeChanging(value);
					this.SendPropertyChanging();
					this._Room_Type = value;
					this.SendPropertyChanged("Room_Type");
					this.OnRoom_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Room_No", DbType="VarChar(50)")]
		public string Room_No
		{
			get
			{
				return this._Room_No;
			}
			set
			{
				if ((this._Room_No != value))
				{
					this.OnRoom_NoChanging(value);
					this.SendPropertyChanging();
					this._Room_No = value;
					this.SendPropertyChanged("Room_No");
					this.OnRoom_NoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No_Of_Person", DbType="VarChar(50)")]
		public string No_Of_Person
		{
			get
			{
				return this._No_Of_Person;
			}
			set
			{
				if ((this._No_Of_Person != value))
				{
					this.OnNo_Of_PersonChanging(value);
					this.SendPropertyChanging();
					this._No_Of_Person = value;
					this.SendPropertyChanged("No_Of_Person");
					this.OnNo_Of_PersonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Children", DbType="VarChar(50)")]
		public string Children
		{
			get
			{
				return this._Children;
			}
			set
			{
				if ((this._Children != value))
				{
					this.OnChildrenChanging(value);
					this.SendPropertyChanging();
					this._Children = value;
					this.SendPropertyChanged("Children");
					this.OnChildrenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Staying_Days", DbType="VarChar(50)")]
		public string Staying_Days
		{
			get
			{
				return this._Staying_Days;
			}
			set
			{
				if ((this._Staying_Days != value))
				{
					this.OnStaying_DaysChanging(value);
					this.SendPropertyChanging();
					this._Staying_Days = value;
					this.SendPropertyChanged("Staying_Days");
					this.OnStaying_DaysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="VarChar(50)")]
		public string Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this.OnTotalChanging(value);
					this.SendPropertyChanging();
					this._Total = value;
					this.SendPropertyChanged("Total");
					this.OnTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Other_Charges", DbType="VarChar(50)")]
		public string Other_Charges
		{
			get
			{
				return this._Other_Charges;
			}
			set
			{
				if ((this._Other_Charges != value))
				{
					this.OnOther_ChargesChanging(value);
					this.SendPropertyChanging();
					this._Other_Charges = value;
					this.SendPropertyChanged("Other_Charges");
					this.OnOther_ChargesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sub_Total", DbType="VarChar(50)")]
		public string Sub_Total
		{
			get
			{
				return this._Sub_Total;
			}
			set
			{
				if ((this._Sub_Total != value))
				{
					this.OnSub_TotalChanging(value);
					this.SendPropertyChanging();
					this._Sub_Total = value;
					this.SendPropertyChanged("Sub_Total");
					this.OnSub_TotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="VarChar(50)")]
		public string Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
